version: "2"

services:
  nginx:
    build: .
    restart: always
    environment:
      NGINX_BACKEND_HOST: redaxo
    depends_on:
      - redaxo
    volumes:
      - doc_root:/var/www/html
    ports:
      - 80:80
  redaxo:
    image: tomcat2111/redaxo
    restart: always
    volumes:
      - doc_root:/var/www/html
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: redaxo
      MYSQL_DATABASE: redaxo
      MYSQL_USER: redaxo
      MYSQL_PASSWORD: redaxo
    volumes:
      - db_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    depends_on:
      - mysql
    environment:
      MYSQL_ROOT_PASSWORD: redaxo
      PMA_HOST: mysql
  webdav:
    image: sashgorokhov/webdav
    restart: always
    ports:
      - 8888:80
    volumes:
      - doc_root:/media
    environment:
      USERNAME: redaxo
      PASSWORD: redaxo
volumes:
  doc_root:
  db_data: