version: "2"

services:
  nginx:
    build: .
    restart: always
    environment:
      NGINX_BACKEND_HOST: redaxo
    depends_on:
      - redaxo
    volumes:
      - root:/var/www/html
    ports:
      - 80:80
  redaxo:
    image: tomcat2111/redaxo
    restart: always
    volumes:
      - root:/var/www/html
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: redaxo
      MYSQL_DATABASE: redaxo
      MYSQL_USER: redaxo
      MYSQL_PASSWORD: redaxo
volumes:
  root: